#!/usr/bin/env python3

import argparse
from datetime import datetime
import ipaddress
import logging
import os
import re
import subprocess
from pathlib import Path
from typing import Dict, List, Tuple

import yaml


logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")
log = logging.getLogger("polysquid")

BASE_DIR = Path(os.getcwd())
SUDO = [] if os.geteuid() == 0 else ["sudo"]
IMAGE = os.getenv("POLYSQUID_IMAGE", "ubuntu/squid:6.13-25.04_beta")

TEMPLATE_CONF = """# Generated by polysquid.py — do not edit by hand
# Minimal Squid config; per-service ACLs appended below.
http_port 3128
cache_dir ufs /var/spool/squid 100 16 256
access_log /var/log/squid/access.log
cache_log /var/log/squid/cache.log
# Default tag for breadth ACL; refined below
# Note: We intentionally create 'allowed_ips' in all cases to simplify rules.
# If no allowed_ips provided for the service, we allow all sources (compatibility
# with the original script's behavior).
"""


# Core helpers used throughout generation and reconciliation.
def run(cmd: List[str], check: bool = False, ignore_err: bool = False) -> subprocess.CompletedProcess:
    """
    Run a command via subprocess.run with logging.
    """
    log.debug(f"RUN: {' '.join(cmd)} (check={check}, ignore_err={ignore_err})")
    try:
        return subprocess.run(cmd, check=check)
    except subprocess.CalledProcessError as e:
        if ignore_err:
            return e  # type: ignore
        raise


def safe_service_name(name: str, fallback: str = "") -> str:
    cleaned = re.sub(r"[^A-Za-z0-9_-]", "", name.replace(" ", "_"))
    if not cleaned:
        cleaned = fallback or "service"
    return cleaned


def load_yaml(path: Path) -> Dict:
    try:
        with path.open() as f:
            data = yaml.safe_load(f)
        if not isinstance(data, dict) or "services" not in data:
            raise ValueError("Invalid services.yaml: must have 'services' key")
        return data
    except (FileNotFoundError, yaml.YAMLError, ValueError) as e:
        log.error(f"Error loading {path}: {e}")
        raise SystemExit(1)


def resolve_shared_calendar(value: str, shared_or_calendars: Dict) -> str:
    """
    Replace 'shared.calendars.X' with the string value from shared.calendars (or calendars dict).
    Returns value unchanged if not a shared reference.
    """
    if not value or not isinstance(value, str):
        return ""
    if value.startswith("shared.calendars."):
        key = value.split(".", 2)[2]
        # Accept either whole 'shared' dict or just the calendars dict
        if isinstance(shared_or_calendars, dict) and "calendars" in shared_or_calendars:
            calendars = shared_or_calendars.get("calendars", {})
        else:
            calendars = shared_or_calendars if isinstance(shared_or_calendars, dict) else {}
        return str(calendars.get(key, "")).strip()
    return value.strip()


def resolve_shared_lists(items, shared: Dict) -> List[str]:
    """
    Expand 'shared.lists.X' entries into their items, flattening and preserving order.
    Non-string entries are ignored. Duplicates removed while preserving order.
    """
    if not items:
        return []
    out: List[str] = []
    seen = set()
    lists = shared.get("lists", {}) if isinstance(shared, dict) else {}
    for itm in items:
        if not isinstance(itm, str):
            log.warning(f"Ignoring non-string list item: {itm}")
            continue
        if itm.startswith("shared.lists."):
            key = itm.split(".", 2)[2]
            expanded = lists.get(key, [])
            if not isinstance(expanded, list):
                log.warning(f"Ignoring invalid shared list '{itm}' (not a list)")
                continue
            for d in expanded:
                if isinstance(d, str) and d and " " not in d and d not in seen:
                    out.append(d)
                    seen.add(d)
                else:
                    log.warning(f"Ignoring invalid domain '{d}' from {itm}")
        else:
            if itm and " " not in itm and itm not in seen:
                out.append(itm)
                seen.add(itm)
            else:
                log.warning(f"Ignoring invalid domain '{itm}'")
    return out


def validate_allowed_ips(allowed_ips) -> List[str]:
    """
    Validate allowed_ips are IPs or CIDRs.
    """
    if allowed_ips is None:
        return []
    valid = []
    for ip in allowed_ips:
        try:
            s = str(ip)
            if "/" in s:
                ipaddress.ip_network(s, strict=False)
            else:
                ipaddress.ip_address(s)
            valid.append(s)
        except Exception:
            log.warning(f"Ignoring invalid allowed_ip '{ip}'")
    return valid


def parse_calendar_ranges(calendar: str) -> Tuple[List[str], List[str]]:
    """
    Parse expressions like:
      "Mon..Fri 08:00..18:00"
      "Mon..Fri 08:00..18:00, Sat 09:00..12:00"
    Returns two lists: (start_specs, stop_specs),
    where each item is a valid OnCalendar entry like "Mon..Fri 08:00".
    If invalid, both lists are empty.
    """
    if not calendar:
        return [], []
    # Split on commas or semicolons to allow multiple segments
    segments = [seg.strip() for seg in re.split(r"[;,]", calendar) if seg.strip()]
    start_specs, stop_specs = [], []
    for seg in segments:
        parts = seg.split()
        if len(parts) == 2:
            days, timerange = parts
        elif len(parts) == 1:
            # No explicit days, only time range (interpreted as daily)
            days, timerange = "", parts[0]
        else:
            log.warning(f"Invalid calendar segment '{seg}', expected 'DAYS TIME1..TIME2' or 'TIME1..TIME2'")
            continue
        if ".." not in timerange:
            log.warning(f"Invalid timerange in calendar segment '{seg}', missing '..'")
            continue
        start_time, end_time = [t.strip() for t in timerange.split("..", 1)]
        start_specs.append(f"{days + ' ' if days else ''}{start_time}")
        stop_specs.append(f"{days + ' ' if days else ''}{end_time}")
    return start_specs, stop_specs


def _parse_clock(value: str):
    for fmt in ("%H:%M:%S", "%H:%M"):
        try:
            return datetime.strptime(value, fmt).time()
        except ValueError:
            continue
    return None


def _expand_days(days_spec: str) -> List[int]:
    day_map = {"Mon": 0, "Tue": 1, "Wed": 2, "Thu": 3, "Fri": 4, "Sat": 5, "Sun": 6}
    if not days_spec:
        return list(range(7))
    if ".." in days_spec:
        start_name, end_name = [d.strip()[:3] for d in days_spec.split("..", 1)]
        if start_name not in day_map or end_name not in day_map:
            return []
        start_idx = day_map[start_name]
        end_idx = day_map[end_name]
        if start_idx <= end_idx:
            return list(range(start_idx, end_idx + 1))
        return list(range(start_idx, 7)) + list(range(0, end_idx + 1))
    single = days_spec.strip()[:3]
    if single not in day_map:
        return []
    return [day_map[single]]


def is_service_active_now(calendar: str) -> bool:
    """
    Return True when current local time falls inside any active calendar segment.
    Supports segments in the same grammar as parse_calendar_ranges.
    """
    if not calendar:
        return True

    now = datetime.now()
    now_day = now.weekday()  # Mon=0 ... Sun=6
    now_time = now.time()

    segments = [seg.strip() for seg in re.split(r"[;,]", calendar) if seg.strip()]
    for seg in segments:
        parts = seg.split()
        if len(parts) == 2:
            days_spec, timerange = parts
        elif len(parts) == 1:
            days_spec, timerange = "", parts[0]
        else:
            continue

        if ".." not in timerange:
            continue

        start_s, end_s = [t.strip() for t in timerange.split("..", 1)]
        start_t = _parse_clock(start_s)
        end_t = _parse_clock(end_s)
        if not start_t or not end_t:
            continue

        active_days = _expand_days(days_spec)
        if not active_days:
            continue

        if start_t <= end_t:
            if now_day in active_days and start_t <= now_time < end_t:
                return True
        else:
            previous_day = (now_day - 1) % 7
            if (now_day in active_days and now_time >= start_t) or (previous_day in active_days and now_time < end_t):
                return True

    return False


# Normalize a raw service entry into the structure the rest of the script expects.
def validate_service(service: Dict, shared: Dict) -> Dict:
    required = ["name", "port", "enabled"]
    for key in required:
        if key not in service:
            log.warning(f"Skipping service: missing '{key}'")
            return {}
    # Port
    try:
        port = int(service["port"])
        if port < 1 or port > 65535:
            raise ValueError
    except Exception:
        log.warning(f"Skipping service '{service.get('name','unknown')}': invalid port")
        return {}
    # Enabled
    enabled = bool(service["enabled"])
    # Allowed IPs
    allowed_ips = validate_allowed_ips(service.get("allowed_ips", []))
    # Whitelist/Blacklist with shared lists expanded
    whitelist = resolve_shared_lists(service.get("whitelist", []), shared)
    blacklist = resolve_shared_lists(service.get("blacklist", []), shared)

    # Calendar (resolve shared and parse)
    calendar_raw = service.get("on_calendar", "")
    calendar_resolved = resolve_shared_calendar(calendar_raw, shared)

    # Return validated
    return {
        "name": service["name"],
        "port": port,
        "enabled": enabled,
        "calendar": calendar_resolved,
        "allowed_ips": allowed_ips,
        "whitelist": whitelist,
        "blacklist": blacklist,
    }


def generate_squid_conf(conf_path: Path, allowed_ips: List[str], whitelist: List[str], blacklist: List[str]) -> None:
    """
    Build squid.conf with proper ordering:
    - If whitelist provided: only allow those domains (whitelist takes precedence over blacklist).
    - Deny blacklist after whitelist allow so whitelist overrides.
    - Combine source and destination ACLs so source restrictions aren't bypassed.
    - If no allowed_ips given, allow all (compatibility with original script).
    """
    lines = [TEMPLATE_CONF]
    # ACLs
    if allowed_ips:
        lines.append("acl allowed_ips src " + " ".join(allowed_ips))
    else:
        # Compatibility with original script where 'localnet src all' allowed everyone
        lines.append("acl allowed_ips src all")
    if whitelist:
        lines.append("acl whitelist dstdomain " + " ".join(whitelist))
    if blacklist:
        lines.append("acl blacklist dstdomain " + " ".join(blacklist))
    lines.append("")  # spacer
    # Access rules
    if whitelist:
        # Allow whitelisted domains only, restricted by source
        lines.append("# Allow only whitelisted destinations (sources restricted via allowed_ips)")
        lines.append("http_access allow allowed_ips whitelist")
        if blacklist:
            # Whitelist precedence over blacklist: deny blacklist after the allow above
            lines.append("http_access deny blacklist")
        # No broad allow here; non-whitelisted destinations will be denied by the final deny all
    else:
        # No whitelist: deny blacklist first, then allow by source
        if blacklist:
            lines.append("http_access deny blacklist")
        lines.append("http_access allow allowed_ips")
    lines.append("http_access deny all")

    conf_path.write_text("\n".join(lines))
def write_systemd_units(
    base_dir: Path,
    systemd_dir: Path,
    conf_dir: Path,
    log_dir: Path,
    cache_dir: Path,
    name: str,
    safe_name: str,
    port: int,
    image: str,
    calendar: str,
) -> Tuple[Path, Path, Path, Path, Path]:
    """
    Write the .service, start timer, stop .service (oneshot), and stop timer.
    Returns paths: (service_file, start_timer_file, stop_service_file, stop_timer_file, logrotate_file)
    """
    # These files are generated under squid-clients/<service>/ and later symlinked into live locations.
    service_file = systemd_dir / f"squid-{safe_name}.service"
    start_timer_file = systemd_dir / f"squid-{safe_name}-start.timer"
    stop_service_file = systemd_dir / f"squid-{safe_name}-stop.service"
    stop_timer_file = systemd_dir / f"squid-{safe_name}-stop.timer"
    logrotate_dir = systemd_dir.parent / "logrotate"
    logrotate_dir.mkdir(parents=True, exist_ok=True)
    logrotate_file = logrotate_dir / f"squid-{safe_name}.logrotate"

    # Main unit for container
    service_content = f"""[Unit]
Description=Squid Docker instance for {name}
After=docker.service network-online.target
Requires=docker.service
[Service]
Type=simple
Restart=no
# Keep stop bounded so timer-driven shutdowns do not hang indefinitely.
TimeoutStopSec=30
# Ensure stale containers are removed before starting
ExecStartPre=-/usr/bin/docker rm -f squid_{safe_name}
ExecStart=/usr/bin/docker run \\
  --name squid_{safe_name} \\
  -v {conf_dir}/squid.conf:/etc/squid/squid.conf \\
  -v {log_dir}:/var/log/squid \\
  -v {cache_dir}:/var/spool/squid \\
  -p {port}:3128 \\
  {image}
ExecStop=/usr/bin/docker stop -t 20 squid_{safe_name}
ExecStopPost=-/usr/bin/docker rm -f squid_{safe_name}
"""
    service_file.write_text(service_content)

    # Timers (if calendar provided)
    if calendar:
        start_specs, stop_specs = parse_calendar_ranges(calendar)
        start_timer_lines = [
            "[Unit]",
            f"Description=Start squid-{safe_name} on schedule",
            "",
            "[Timer]",
        ]
        # If no parsed segments, keep one invalid line to force a systemd error? Better: log and skip timers.
        if start_specs:
            for spec in start_specs:
                start_timer_lines.append(f"OnCalendar={spec}")
        else:
            log.warning(f"Invalid calendar '{calendar}', skipping timers for {name}")
        start_timer_lines += [
            "AccuracySec=1sec",
            f"Unit=squid-{safe_name}.service",
            "",
            "[Install]",
            "WantedBy=timers.target",
            "",
        ]
        start_timer_file.write_text("\n".join(start_timer_lines))

        # A oneshot service to stop the main unit
        stop_service_content = f"""[Unit]
Description=Stop squid-{safe_name} (oneshot)
Wants=squid-{safe_name}.service
[Service]
Type=oneshot
ExecStart=/bin/systemctl stop squid-{safe_name}.service
[Install]
WantedBy=multi-user.target
"""
        stop_service_file.write_text(stop_service_content)
        stop_timer_lines = [
            "[Unit]",
            f"Description=Stop squid-{safe_name} on schedule",
            "",
            "[Timer]",
        ]
        if stop_specs:
            for spec in stop_specs:
                stop_timer_lines.append(f"OnCalendar={spec}")
        else:
            log.warning(f"Invalid calendar '{calendar}', skipping stop timer for {name}")
        stop_timer_lines += [
            "AccuracySec=1sec",
            f"Unit=squid-{safe_name}-stop.service",
            "",
            "[Install]",
            "WantedBy=timers.target",
            "",
        ]
        stop_timer_file.write_text("\n".join(stop_timer_lines))

    # Logrotate: signal the container (USR1) to rotate logs
    logrotate_content = f"""{base_dir}/squid-clients/{safe_name}/logs/*.log {{
    daily
    rotate 30
    compress
    missingok
    notifempty
    delaycompress
    nocreate
    sharedscripts
    postrotate
        /usr/bin/docker kill -s USR1 squid_{safe_name} >/dev/null 2>&1 || true
    endscript
}}
"""
    logrotate_file.write_text(logrotate_content)

    return service_file, start_timer_file, stop_service_file, stop_timer_file, logrotate_file


# Remove units for services no longer declared in services.yaml.
def cleanup_removed_services(active_safe_names: List[str]):
    systemd_path = Path("/etc/systemd/system")
    suffixes = [".service", "-start.timer", "-stop.timer", "-stop.service"]

    for unit in systemd_path.glob("squid-*.service"):
        # Ignore helper stop units; they are tied to their parent service name.
        if unit.name.endswith("-stop.service"):
            continue

        svc_name = unit.stem.replace("squid-", "")
        if svc_name not in active_safe_names:
            log.info(f"Removing stale service '{svc_name}'")
            run(SUDO + ["systemctl", "disable", "--now", f"squid-{svc_name}.service"], ignore_err=True)
            for suf in suffixes:
                run(SUDO + ["rm", "-f", str(systemd_path / f"squid-{svc_name}{suf}")], ignore_err=True)
            run(SUDO + ["rm", "-f", f"/etc/logrotate.d/squid-{svc_name}"], ignore_err=True)

    run(SUDO + ["systemctl", "daemon-reload"], check=False)


def main():
    parser = argparse.ArgumentParser(description="Generate per-client Squid systemd units and config")
    parser.add_argument("-c", "--config", default="services.yaml", help="Path to services.yaml")
    parser.add_argument("--base-dir", default=str(BASE_DIR), help="Base output dir (default: CWD)")
    parser.add_argument("--image", default=IMAGE, help="Docker image to use (env POLYSQUID_IMAGE overrides default)")
    parser.add_argument("-v", "--verbose", action="store_true", help="Verbose logging")

    args = parser.parse_args()
    if args.verbose:
        log.setLevel(logging.DEBUG)

    base_dir = Path(args.base_dir).resolve()
    data = load_yaml(Path(args.config))
    services = data.get("services", [])
    shared = data.get("shared", {})

    # Check duplicates
    ports_seen = {}
    names_seen = set()
    for svc in services:
        name = svc.get("name", "")
        port = svc.get("port", None)
        if name in names_seen:
            log.warning(f"Duplicate service name '{name}' found. Later entries may overwrite files.")
        else:
            names_seen.add(name)

        if port is not None:
            try:
                ports_seen.setdefault(int(port), []).append(name)
            except (TypeError, ValueError):
                log.warning(f"Skipping duplicate-port precheck for service '{name}': invalid port '{port}'")

    for p, names in ports_seen.items():
        if len(names) > 1:
            log.warning(f"Port {p} used by multiple services: {', '.join(names)}")

    active_safe_names = []

    # Reconcile each declared service into generated config, systemd units, and active state.
    for service in services:
        validated = validate_service(service, shared)
        if not validated:
            continue

        name = validated["name"]
        port = validated["port"]
        enabled = validated["enabled"]
        calendar = validated["calendar"]
        allowed_ips = validated["allowed_ips"]
        whitelist = validated["whitelist"]
        blacklist = validated["blacklist"]
        safe_name = safe_service_name(name, fallback=f"squid_{port}")

        # Layout
        client_dir = base_dir / "squid-clients" / safe_name
        systemd_dir = client_dir / "systemd"
        conf_dir = client_dir / "conf"
        log_dir = client_dir / "logs"
        cache_dir = client_dir / "cache"

        for d in [systemd_dir, conf_dir, log_dir, cache_dir]:
            d.mkdir(parents=True, exist_ok=True)

        # Permissions for Squid user inside docker (proxy uid/gid = 13)
        run(SUDO + ["chown", "-R", "13:13", str(log_dir)], ignore_err=True)
        run(SUDO + ["chown", "-R", "13:13", str(cache_dir)], ignore_err=True)

        # squid.conf
        generate_squid_conf(conf_dir / "squid.conf", allowed_ips, whitelist, blacklist)

        # Systemd + logrotate files
        service_file, start_timer_file, stop_service_file, stop_timer_file, logrotate_file = write_systemd_units(
            base_dir=base_dir,
            systemd_dir=systemd_dir,
            conf_dir=conf_dir,
            log_dir=log_dir,
            cache_dir=cache_dir,
            name=name,
            safe_name=safe_name,
            port=port,
            image=args.image,
            calendar=calendar,
        )

        # Clean old symlinks
        run(SUDO + ["rm", "-f", f"/etc/systemd/system/squid-{safe_name}.service"])
        run(SUDO + ["rm", "-f", f"/etc/systemd/system/squid-{safe_name}-start.timer"])
        run(SUDO + ["rm", "-f", f"/etc/systemd/system/squid-{safe_name}-stop.timer"])
        run(SUDO + ["rm", "-f", f"/etc/systemd/system/squid-{safe_name}-stop.service"])
        run(SUDO + ["rm", "-f", f"/etc/logrotate.d/squid-{safe_name}"])

        if enabled:
            log.info(f"Enabled: {name}")

            # Link generated artifacts into the live systemd and logrotate locations.
            run(SUDO + ["ln", "-s", str(service_file), f"/etc/systemd/system/squid-{safe_name}.service"])

            # Timers and stop unit are only used when the service has a schedule.
            if calendar:
                if start_timer_file.exists():
                    run(SUDO + ["ln", "-s", str(start_timer_file), f"/etc/systemd/system/squid-{safe_name}-start.timer"])
                if stop_service_file.exists():
                    run(SUDO + ["ln", "-s", str(stop_service_file), f"/etc/systemd/system/squid-{safe_name}-stop.service"])
                if stop_timer_file.exists():
                    run(SUDO + ["ln", "-s", str(stop_timer_file), f"/etc/systemd/system/squid-{safe_name}-stop.timer"])

                run(SUDO + ["ln", "-s", str(logrotate_file), f"/etc/logrotate.d/squid-{safe_name}"], ignore_err=True)
                run(SUDO + ["systemctl", "daemon-reload"], check=False)
                if start_timer_file.exists():
                    run(SUDO + ["systemctl", "enable", "--now", f"squid-{safe_name}-start.timer"], check=False)
                if stop_timer_file.exists():
                    run(SUDO + ["systemctl", "enable", "--now", f"squid-{safe_name}-stop.timer"], check=False)

                # Ensure correct state now (install/run time), independent of timer catch-up behavior.
                if is_service_active_now(calendar):
                    run(SUDO + ["systemctl", "start", f"squid-{safe_name}.service"], check=False)
                else:
                    run(SUDO + ["systemctl", "stop", f"squid-{safe_name}.service"], ignore_err=True)
            else:
                run(SUDO + ["ln", "-s", str(logrotate_file), f"/etc/logrotate.d/squid-{safe_name}"], ignore_err=True)
                run(SUDO + ["systemctl", "daemon-reload"], check=False)
                run(SUDO + ["systemctl", "enable", "--now", f"squid-{safe_name}.service"], check=False)
        else:
            log.info(f"Disabled: {name}")

            # Disabled services are stopped and left without active systemd links.
            run(SUDO + ["systemctl", "disable", "--now", f"squid-{safe_name}.service"], ignore_err=True)
            run(SUDO + ["systemctl", "disable", "--now", f"squid-{safe_name}-start.timer"], ignore_err=True)
            run(SUDO + ["systemctl", "disable", "--now", f"squid-{safe_name}-stop.timer"], ignore_err=True)
            run(SUDO + ["rm", "-f", f"/etc/logrotate.d/squid-{safe_name}"], ignore_err=True)
            run(SUDO + ["systemctl", "daemon-reload"], check=False)

        active_safe_names.append(safe_name)

    cleanup_removed_services(active_safe_names)
    print("All entries processed.")


if __name__ == "__main__":
    main()