#!/usr/bin/env python3

import argparse
from datetime import datetime, timezone
import ipaddress
import json
import logging
import os
import re
import subprocess
from pathlib import Path
from typing import Dict, List, Optional, Tuple

import yaml


logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")
log = logging.getLogger("polysquid")

BASE_DIR = Path(os.getcwd())
SUDO = [] if os.geteuid() == 0 else ["sudo"]
IMAGE = os.getenv("POLYSQUID_IMAGE", "polysquid-squid:debian-openssl")

TEMPLATE_CONF = """# Generated by polysquid.py — do not edit by hand
# Minimal Squid config; per-service ACLs appended below.
cache_dir ufs /var/spool/squid 100 16 256
access_log /var/log/squid/access.log
cache_log /var/log/squid/cache.log
# Default tag for breadth ACL; refined below
# Note: We intentionally create 'allowed_ips' in all cases to simplify rules.
# If no allowed_ips provided for the service, we allow all sources (compatibility
# with the original script's behavior).
"""


# Core helpers used throughout generation and reconciliation.
def run(cmd: List[str], check: bool = False, ignore_err: bool = False) -> subprocess.CompletedProcess:
    """
    Run a command via subprocess.run with logging.
    """
    log.debug(f"RUN: {' '.join(cmd)} (check={check}, ignore_err={ignore_err})")
    try:
        return subprocess.run(cmd, check=check)
    except subprocess.CalledProcessError as e:
        if ignore_err:
            return e  # type: ignore
        raise


def safe_service_name(name: str, fallback: str = "") -> str:
    cleaned = re.sub(r"[^A-Za-z0-9_-]", "", name.replace(" ", "_"))
    if not cleaned:
        cleaned = fallback or "service"
    return cleaned


def load_yaml(path: Path) -> Dict:
    try:
        with path.open() as f:
            data = yaml.safe_load(f)
        if not isinstance(data, dict) or "services" not in data:
            raise ValueError("Invalid services.yaml: must have 'services' key")
        return data
    except (FileNotFoundError, yaml.YAMLError, ValueError) as e:
        log.error(f"Error loading {path}: {e}")
        raise SystemExit(1)


def resolve_shared_calendar(value: str, shared_or_calendars: Dict) -> str:
    """
    Replace 'shared.calendars.X' with the string value from shared.calendars (or calendars dict).
    Returns value unchanged if not a shared reference.
    """
    if not value or not isinstance(value, str):
        return ""
    if value.startswith("shared.calendars."):
        key = value.split(".", 2)[2]
        # Accept either whole 'shared' dict or just the calendars dict
        if isinstance(shared_or_calendars, dict) and "calendars" in shared_or_calendars:
            calendars = shared_or_calendars.get("calendars", {})
        else:
            calendars = shared_or_calendars if isinstance(shared_or_calendars, dict) else {}
        return str(calendars.get(key, "")).strip()
    return value.strip()


def resolve_shared_lists(items, shared: Dict) -> List[str]:
    """
    Expand 'shared.lists.X' entries into their items, flattening and preserving order.
    Non-string entries are ignored. Duplicates removed while preserving order.
    """
    if not items:
        return []
    out: List[str] = []
    seen = set()
    lists = shared.get("lists", {}) if isinstance(shared, dict) else {}
    for itm in items:
        if not isinstance(itm, str):
            log.warning(f"Ignoring non-string list item: {itm}")
            continue
        if itm.startswith("shared.lists."):
            key = itm.split(".", 2)[2]
            expanded = lists.get(key, [])
            if not isinstance(expanded, list):
                log.warning(f"Ignoring invalid shared list '{itm}' (not a list)")
                continue
            for d in expanded:
                if isinstance(d, str) and d and " " not in d and d not in seen:
                    out.append(d)
                    seen.add(d)
                else:
                    log.warning(f"Ignoring invalid domain '{d}' from {itm}")
        else:
            if itm and " " not in itm and itm not in seen:
                out.append(itm)
                seen.add(itm)
            else:
                log.warning(f"Ignoring invalid domain '{itm}'")
    return out


def validate_allowed_ips(allowed_ips) -> List[str]:
    """
    Validate allowed_ips are IPs or CIDRs.
    """
    if allowed_ips is None:
        return []
    valid = []
    for ip in allowed_ips:
        try:
            s = str(ip)
            if "/" in s:
                ipaddress.ip_network(s, strict=False)
            else:
                ipaddress.ip_address(s)
            valid.append(s)
        except Exception:
            log.warning(f"Ignoring invalid allowed_ip '{ip}'")
    return valid


def _is_self_service_name(name: str) -> bool:
    normalized = re.sub(r"[\s_-]+", " ", str(name).strip().lower())
    return normalized == "self service"


def _load_active_self_service_ips(requests_dir: Path) -> List[str]:
    """
    Load active (non-expired) source IPs from self-service request files.
    """
    if not requests_dir.exists():
        return []

    now = datetime.now(timezone.utc)
    active_ips: List[str] = []
    seen = set()

    for request_file in sorted(requests_dir.glob("request_*.json")):
        try:
            with request_file.open() as f:
                req = json.load(f)

            source_ip = str(req.get("source_ip", "")).strip()
            expires_raw = str(req.get("expires_at", "")).strip()
            if not source_ip or not expires_raw:
                continue

            # Keep timestamp parsing compatible with Z-suffixed UTC values.
            expires_at = datetime.fromisoformat(expires_raw.replace("Z", "+00:00"))
            if expires_at <= now:
                continue

            # Reuse existing CIDR/IP validation helper for consistency.
            if not validate_allowed_ips([source_ip]):
                log.warning(f"Ignoring invalid dynamic source_ip '{source_ip}' in {request_file.name}")
                continue

            if source_ip not in seen:
                active_ips.append(source_ip)
                seen.add(source_ip)
        except Exception as e:
            log.warning(f"Ignoring malformed request file {request_file.name}: {e}")

    return active_ips


def parse_calendar_ranges(calendar: str) -> Tuple[List[str], List[str]]:
    """
    Parse expressions like:
      "Mon..Fri 08:00..18:00"
      "Mon..Fri 08:00..18:00, Sat 09:00..12:00"
    Returns two lists: (start_specs, stop_specs),
    where each item is a valid OnCalendar entry like "Mon..Fri 08:00".
    If invalid, both lists are empty.
    """
    if not calendar:
        return [], []
    # Split on commas or semicolons to allow multiple segments
    segments = [seg.strip() for seg in re.split(r"[;,]", calendar) if seg.strip()]
    start_specs, stop_specs = [], []
    for seg in segments:
        parts = seg.split()
        if len(parts) == 2:
            days, timerange = parts
        elif len(parts) == 1:
            # No explicit days, only time range (interpreted as daily)
            days, timerange = "", parts[0]
        else:
            log.warning(f"Invalid calendar segment '{seg}', expected 'DAYS TIME1..TIME2' or 'TIME1..TIME2'")
            continue
        if ".." not in timerange:
            log.warning(f"Invalid timerange in calendar segment '{seg}', missing '..'")
            continue
        start_time, end_time = [t.strip() for t in timerange.split("..", 1)]
        start_specs.append(f"{days + ' ' if days else ''}{start_time}")
        stop_specs.append(f"{days + ' ' if days else ''}{end_time}")
    return start_specs, stop_specs


def _next_elapse(spec: str) -> Optional[datetime]:
    """
    Return the next elapse time (local) for a systemd OnCalendar spec by
    calling systemd-analyze. Returns None if unavailable or no future trigger.
    """
    try:
        result = subprocess.run(
            ["systemd-analyze", "calendar", spec],
            capture_output=True, text=True, timeout=5
        )
        for line in result.stdout.splitlines():
            stripped = line.strip()
            if stripped.startswith("Next elapse:"):
                raw = stripped.split(":", 1)[1].strip()
                # Format: "Mon 2026-03-23 08:00:00 CET" — drop trailing tz token
                parts = raw.split()
                if len(parts) >= 3:
                    return datetime.strptime(f"{parts[0]} {parts[1]} {parts[2]}", "%a %Y-%m-%d %H:%M:%S")
    except Exception:
        pass
    return None


def is_service_active_now(calendar: str) -> bool:
    """
    Return True when the current local time falls inside any active calendar window.
    Delegates calendar parsing to systemd-analyze so the evaluation exactly matches
    the OnCalendar semantics used by the generated timers.

    Strategy: for each start/stop pair, ask systemd when each *next* fires.
    If the next stop is sooner than the next start, we are currently inside the
    window (the start has already passed and the stop has not yet).
    Falls back to False (do not start) if systemd-analyze cannot evaluate.
    """
    if not calendar:
        return True

    start_specs, stop_specs = parse_calendar_ranges(calendar)
    if not start_specs or not stop_specs:
        return False

    for start_spec, stop_spec in zip(start_specs, stop_specs):
        next_start = _next_elapse(start_spec)
        next_stop = _next_elapse(stop_spec)
        if next_start is None or next_stop is None:
            continue
        # Next stop sooner than next start → currently inside the active window.
        if next_stop < next_start:
            return True

    return False


# Normalize a raw service entry into the structure the rest of the script expects.
def validate_service(service: Dict, shared: Dict) -> Dict:
    required = ["name", "port", "enabled"]
    for key in required:
        if key not in service:
            log.warning(f"Skipping service: missing '{key}'")
            return {}
    # Port
    try:
        port = int(service["port"])
        if port < 1 or port > 65535:
            raise ValueError
    except Exception:
        log.warning(f"Skipping service '{service.get('name','unknown')}': invalid port")
        return {}
    use_tls = bool(service.get("use_tls", False))
    # Enabled
    enabled = bool(service["enabled"])
    # Allowed IPs
    allowed_ips = validate_allowed_ips(service.get("allowed_ips", []))
    # Whitelist with shared lists expanded
    whitelist = resolve_shared_lists(service.get("whitelist", []), shared)

    # Calendar (resolve shared and parse)
    calendar_raw = service.get("on_calendar", "")
    calendar_resolved = resolve_shared_calendar(calendar_raw, shared)

    # Return validated
    return {
        "name": service["name"],
        "port": port,
        "use_tls": use_tls,
        "enabled": enabled,
        "calendar": calendar_resolved,
        "allowed_ips": allowed_ips,
        "whitelist": whitelist,
    }


def generate_squid_conf(conf_path: Path, allowed_ips: List[str], whitelist: List[str], use_tls: bool) -> bool:
    """
    Build squid.conf with deny-by-default access control:
    - If whitelist provided: only allow those domains, deny everything else.
    - If no whitelist: allow all from allowed_ips, deny everything else.
    - Combine source and destination ACLs so source restrictions aren't bypassed.
    - If no allowed_ips given, allow all (compatibility with original script).
    """
    lines = [TEMPLATE_CONF]
    if use_tls:
        lines.append("https_port 3128 tls-cert=/etc/squid/tls/fullchain.pem tls-key=/etc/squid/tls/privkey.pem")
    else:
        lines.append("http_port 3128")
    # ACLs
    if allowed_ips:
        lines.append("acl allowed_ips src " + " ".join(allowed_ips))
    else:
        # Compatibility with original script where 'localnet src all' allowed everyone
        lines.append("acl allowed_ips src all")
    if whitelist:
        lines.append("acl whitelist dstdomain " + " ".join(whitelist))
    lines.append("")  # spacer
    # Access rules: deny-by-default
    if whitelist:
        # Allow only whitelisted destinations, restricted by source
        lines.append("# Allow only whitelisted destinations (sources restricted via allowed_ips)")
        lines.append("http_access allow allowed_ips whitelist")
    else:
        # No whitelist: allow all from allowed_ips
        lines.append("http_access allow allowed_ips")
    lines.append("http_access deny all")

    new_content = "\n".join(lines)
    if conf_path.exists() and conf_path.read_text() == new_content:
        return False
    conf_path.write_text(new_content)
    return True


def write_systemd_units(
    base_dir: Path,
    systemd_dir: Path,
    conf_dir: Path,
    log_dir: Path,
    cache_dir: Path,
    name: str,
    safe_name: str,
    port: int,
    use_tls: bool,
    image: str,
    calendar: str,
) -> Tuple[Path, Path, Path, Path, Path]:
    """
    Write the .service, start timer, stop .service (oneshot), and stop timer.
    Returns paths: (service_file, start_timer_file, stop_service_file, stop_timer_file, logrotate_file)
    """
    # These files are generated under squid-clients/<service>/ and later symlinked into live locations.
    service_file = systemd_dir / f"squid-{safe_name}.service"
    start_timer_file = systemd_dir / f"squid-{safe_name}-start.timer"
    stop_service_file = systemd_dir / f"squid-{safe_name}-stop.service"
    stop_timer_file = systemd_dir / f"squid-{safe_name}-stop.timer"
    logrotate_dir = systemd_dir.parent / "logrotate"
    logrotate_dir.mkdir(parents=True, exist_ok=True)
    logrotate_file = logrotate_dir / f"squid-{safe_name}.logrotate"

    # Main unit for container
    tls_mount = ""
    if use_tls:
        tls_mount = "  -v /etc/polysquid/certs:/etc/squid/tls:ro \\\n"

    service_content = f"""[Unit]
Description=Squid Docker instance for {name}
After=docker.service network-online.target
Requires=docker.service
[Service]
Type=simple
Restart=no
# Keep stop bounded so timer-driven shutdowns do not hang indefinitely.
TimeoutStopSec=30
# Ensure stale containers are removed before starting
ExecStartPre=-/usr/bin/docker rm -f squid_{safe_name}
ExecStart=/usr/bin/docker run \\
  --name squid_{safe_name} \\
  -v {conf_dir}/squid.conf:/etc/squid/squid.conf \\
  -v {log_dir}:/var/log/squid \\
  -v {cache_dir}:/var/spool/squid \\
{tls_mount}  -p {port}:3128 \\
    {image}
ExecStop=/usr/bin/docker stop -t 20 squid_{safe_name}
"""
    # Calendar-driven services are started/stopped by their timers; they must NOT have
    # WantedBy=multi-user.target or systemctl enable would start them outside their window.
    # Services without a calendar are always-on and need the Install section.
    if not calendar:
        service_content += "\n[Install]\nWantedBy=multi-user.target\n"
    service_file.write_text(service_content)

    if calendar:
        start_specs, stop_specs = parse_calendar_ranges(calendar)
        start_timer_lines = [
            "[Unit]",
            f"Description=Start squid-{safe_name} on schedule",
            "",
            "[Timer]",
        ]
        # If no parsed segments, keep one invalid line to force a systemd error? Better: log and skip timers.
        if start_specs:
            for spec in start_specs:
                start_timer_lines.append(f"OnCalendar={spec}")
        else:
            log.warning(f"Invalid calendar '{calendar}', skipping timers for {name}")
        start_timer_lines += [
            "AccuracySec=1sec",
            f"Unit=squid-{safe_name}.service",
            "",
            "[Install]",
            "WantedBy=timers.target",
            "",
        ]
        start_timer_file.write_text("\n".join(start_timer_lines))

        # A oneshot service to stop the main unit
        stop_service_content = f"""[Unit]
Description=Stop squid-{safe_name} (oneshot)
Wants=squid-{safe_name}.service
[Service]
Type=oneshot
ExecStart=/bin/systemctl stop squid-{safe_name}.service
[Install]
WantedBy=multi-user.target
"""
        stop_service_file.write_text(stop_service_content)
        stop_timer_lines = [
            "[Unit]",
            f"Description=Stop squid-{safe_name} on schedule",
            "",
            "[Timer]",
        ]
        if stop_specs:
            for spec in stop_specs:
                stop_timer_lines.append(f"OnCalendar={spec}")
        else:
            log.warning(f"Invalid calendar '{calendar}', skipping stop timer for {name}")
        stop_timer_lines += [
            "AccuracySec=1sec",
            f"Unit=squid-{safe_name}-stop.service",
            "",
            "[Install]",
            "WantedBy=timers.target",
            "",
        ]
        stop_timer_file.write_text("\n".join(stop_timer_lines))

    # Logrotate: signal the container (USR1) to rotate logs
    logrotate_content = f"""{base_dir}/squid-clients/{safe_name}/logs/*.log {{
    daily
    rotate 30
    compress
    missingok
    notifempty
    delaycompress
    nocreate
    sharedscripts
    postrotate
        /usr/bin/docker kill -s USR1 squid_{safe_name} >/dev/null 2>&1 || true
    endscript
}}
"""
    logrotate_file.write_text(logrotate_content)

    return service_file, start_timer_file, stop_service_file, stop_timer_file, logrotate_file


# Remove units for services no longer declared in services.yaml.
def cleanup_removed_services(active_safe_names: List[str]):
    systemd_path = Path("/etc/systemd/system")
    suffixes = [".service", "-start.timer", "-stop.timer", "-stop.service"]

    for unit in systemd_path.glob("squid-*.service"):
        # Ignore helper stop units; they are tied to their parent service name.
        if unit.name.endswith("-stop.service"):
            continue

        svc_name = unit.stem.replace("squid-", "")
        if svc_name not in active_safe_names:
            log.info(f"Removing stale service '{svc_name}'")
            run(SUDO + ["systemctl", "disable", "--now", f"squid-{svc_name}.service"], ignore_err=True)
            for suf in suffixes:
                run(SUDO + ["rm", "-f", str(systemd_path / f"squid-{svc_name}{suf}")], ignore_err=True)
            run(SUDO + ["rm", "-f", f"/etc/logrotate.d/squid-{svc_name}"], ignore_err=True)

    run(SUDO + ["systemctl", "daemon-reload"], check=False)


def main():
    parser = argparse.ArgumentParser(description="Generate per-client Squid systemd units and config")
    parser.add_argument("-c", "--config", default="services.yaml", help="Path to services.yaml")
    parser.add_argument("--base-dir", default=str(BASE_DIR), help="Base output dir (default: CWD)")
    parser.add_argument("--image", default=IMAGE, help="Docker image to use (env POLYSQUID_IMAGE overrides default)")
    parser.add_argument("-v", "--verbose", action="store_true", help="Verbose logging")

    args = parser.parse_args()
    if args.verbose:
        log.setLevel(logging.DEBUG)

    base_dir = Path(args.base_dir).resolve()
    data = load_yaml(Path(args.config))
    services = data.get("services", [])
    shared = data.get("shared", {})

    # Check duplicates
    ports_seen = {}
    names_seen = set()
    for svc in services:
        name = svc.get("name", "")
        port = svc.get("port", None)
        if name in names_seen:
            log.warning(f"Duplicate service name '{name}' found. Later entries may overwrite files.")
        else:
            names_seen.add(name)

        if port is not None:
            try:
                ports_seen.setdefault(int(port), []).append(name)
            except (TypeError, ValueError):
                log.warning(f"Skipping duplicate-port precheck for service '{name}': invalid port '{port}'")

    for p, names in ports_seen.items():
        if len(names) > 1:
            log.warning(f"Port {p} used by multiple services: {', '.join(names)}")

    active_safe_names = []

    # Reconcile each declared service into generated config, systemd units, and active state.
    for service in services:
        validated = validate_service(service, shared)
        if not validated:
            continue

        name = validated["name"]
        port = validated["port"]
        use_tls = validated["use_tls"]
        enabled = validated["enabled"]
        calendar = validated["calendar"]
        allowed_ips = validated["allowed_ips"]
        whitelist = validated["whitelist"]
        safe_name = safe_service_name(name, fallback=f"squid_{port}")

        # Merge active self-service request IPs into allowed_ips for the Self service proxy.
        if _is_self_service_name(name):
            requests_dir = base_dir / "self-service" / "requests"
            dynamic_ips = _load_active_self_service_ips(requests_dir)
            if dynamic_ips:
                allowed_ips = list(dict.fromkeys(allowed_ips + dynamic_ips))
                log.info(f"Merged {len(dynamic_ips)} active self-service request IP(s) into {name}")

        # Layout
        client_dir = base_dir / "squid-clients" / safe_name
        systemd_dir = client_dir / "systemd"
        conf_dir = client_dir / "conf"
        log_dir = client_dir / "logs"
        cache_dir = client_dir / "cache"

        for d in [systemd_dir, conf_dir, log_dir, cache_dir]:
            d.mkdir(parents=True, exist_ok=True)

        # Permissions for Squid user inside docker (proxy uid/gid = 13)
        run(SUDO + ["chown", "-R", "13:13", str(log_dir)], ignore_err=True)
        run(SUDO + ["chown", "-R", "13:13", str(cache_dir)], ignore_err=True)

        # squid.conf
        conf_changed = generate_squid_conf(conf_dir / "squid.conf", allowed_ips, whitelist, use_tls)
        if conf_changed:
            # Signal running container to reload config without restart (squid -k reconfigure).
            r = run(SUDO + ["systemctl", "is-active", "--quiet", f"squid-{safe_name}.service"])
            if r.returncode == 0:
                run(SUDO + ["/usr/bin/docker", "kill", "-s", "HUP", f"squid_{safe_name}"], ignore_err=True)
                log.info(f"Config changed for {name}: sent SIGHUP to reload")

        # Systemd + logrotate files
        service_file, start_timer_file, stop_service_file, stop_timer_file, logrotate_file = write_systemd_units(
            base_dir=base_dir,
            systemd_dir=systemd_dir,
            conf_dir=conf_dir,
            log_dir=log_dir,
            cache_dir=cache_dir,
            name=name,
            safe_name=safe_name,
            port=port,
            use_tls=use_tls,
            image=args.image,
            calendar=calendar,
        )

        # Clean old symlinks
        run(SUDO + ["rm", "-f", f"/etc/systemd/system/squid-{safe_name}.service"])
        run(SUDO + ["rm", "-f", f"/etc/systemd/system/squid-{safe_name}-start.timer"])
        run(SUDO + ["rm", "-f", f"/etc/systemd/system/squid-{safe_name}-stop.timer"])
        run(SUDO + ["rm", "-f", f"/etc/systemd/system/squid-{safe_name}-stop.service"])
        run(SUDO + ["rm", "-f", f"/etc/logrotate.d/squid-{safe_name}"])

        if enabled:
            log.info(f"Enabled: {name}")

            # Link generated artifacts into the live systemd and logrotate locations.
            run(SUDO + ["ln", "-s", str(service_file), f"/etc/systemd/system/squid-{safe_name}.service"])

            # Timers and stop unit are only used when the service has a schedule.
            if calendar:
                if start_timer_file.exists():
                    run(SUDO + ["ln", "-s", str(start_timer_file), f"/etc/systemd/system/squid-{safe_name}-start.timer"])
                if stop_service_file.exists():
                    run(SUDO + ["ln", "-s", str(stop_service_file), f"/etc/systemd/system/squid-{safe_name}-stop.service"])
                if stop_timer_file.exists():
                    run(SUDO + ["ln", "-s", str(stop_timer_file), f"/etc/systemd/system/squid-{safe_name}-stop.timer"])

                run(SUDO + ["ln", "-s", str(logrotate_file), f"/etc/logrotate.d/squid-{safe_name}"], ignore_err=True)
                run(SUDO + ["systemctl", "daemon-reload"], check=False)
                if start_timer_file.exists():
                    run(SUDO + ["systemctl", "enable", "--now", f"squid-{safe_name}-start.timer"], check=False)
                if stop_timer_file.exists():
                    run(SUDO + ["systemctl", "enable", "--now", f"squid-{safe_name}-stop.timer"], check=False)

                # Ensure correct state now (install/run time), independent of timer catch-up behavior.
                if is_service_active_now(calendar):
                    run(SUDO + ["systemctl", "start", f"squid-{safe_name}.service"], check=False)
                else:
                    # Only stop if actually running to suppress the "triggering units still active"
                    # advisory systemd emits when stopping a service while its timer is armed.
                    is_active = run(SUDO + ["systemctl", "is-active", "--quiet", f"squid-{safe_name}.service"])
                    if is_active.returncode == 0:
                        run(SUDO + ["systemctl", "stop", f"squid-{safe_name}.service"], ignore_err=True)
            else:
                run(SUDO + ["ln", "-s", str(logrotate_file), f"/etc/logrotate.d/squid-{safe_name}"], ignore_err=True)
                run(SUDO + ["systemctl", "daemon-reload"], check=False)
                run(SUDO + ["systemctl", "enable", "--now", f"squid-{safe_name}.service"], check=False)
        else:
            log.info(f"Disabled: {name}")

            # Disabled services are stopped and left without active systemd links.
            run(SUDO + ["systemctl", "disable", "--now", f"squid-{safe_name}.service"], ignore_err=True)
            run(SUDO + ["systemctl", "disable", "--now", f"squid-{safe_name}-start.timer"], ignore_err=True)
            run(SUDO + ["systemctl", "disable", "--now", f"squid-{safe_name}-stop.timer"], ignore_err=True)
            run(SUDO + ["rm", "-f", f"/etc/logrotate.d/squid-{safe_name}"], ignore_err=True)
            run(SUDO + ["systemctl", "daemon-reload"], check=False)

        active_safe_names.append(safe_name)

    cleanup_removed_services(active_safe_names)
    print("All entries processed.")


if __name__ == "__main__":
    main()